trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildApp
    displayName: Build App
    jobs:
      - job: BuildFunctionApp
        displayName: Build Function App
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: Build and Push Image
            inputs:
              azureSubscription: '$(SERVICE_NAME)'
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              inlineScript: |
                az acr build `
                  -f $(System.DefaultWorkingDirectory)/src/Dockerfile `
                  -t $(DOCKER_IMAGE_NAME) `
                  -r $(ACR_NAME) ./src

  - stage: DeployApp
    displayName: Deploy App
    jobs:
      - job: InfraFunctionApp
        displayName: Deploy Infrastructure
        steps:
          - checkout: self
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: '$(SERVICE_NAME)'
              subscriptionId: $(AZURE_SUBSCRIPTION_ID)
              action: "Create Or Update Resource Group"
              resourceGroupName: $(RESOURCE_GROUP_NAME)
              location: $(LOCATION)
              templateLocation: "Linked artifact"
              csmFile: $(System.DefaultWorkingDirectory)/infra/main.bicep
              overrideParameters: 
                -resourceNamePrefix $(RESOURCE_NAME_PREFIX)
                -acrName $(ACR_NAME)
                -dockerImage $(DOCKER_IMAGE_NAME)
              deploymentMode: "Incremental"

